//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//
//
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_SlaveSelect_MasterInterface_2 (
    input [2:0] slave_select,
    input [2:0] slave_select_delayed,
    input [2:0] HSIZE,
    input [1:0] HTRANS,
    output reg  HRESP,
    output reg  HREADY,
    input HSEL,
    input HWRITE,
    output reg  [31:0] HRDATA,
    input [31:0] HWDATA,
    output reg  [2:0] AHB_Lite_SlaveInterface_A_HSIZE,
    output reg  [1:0] AHB_Lite_SlaveInterface_A_HTRANS,
    input AHB_Lite_SlaveInterface_A_HRESP,
    input AHB_Lite_SlaveInterface_A_HREADY,
    output reg  AHB_Lite_SlaveInterface_A_HSEL,
    output reg  AHB_Lite_SlaveInterface_A_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_A_HRDATA,
    output reg  [31:0] AHB_Lite_SlaveInterface_A_HWDATA,
    output reg  [2:0] AHB_Lite_SlaveInterface_B_HSIZE,
    output reg  [1:0] AHB_Lite_SlaveInterface_B_HTRANS,
    input AHB_Lite_SlaveInterface_B_HRESP,
    input AHB_Lite_SlaveInterface_B_HREADY,
    output reg  AHB_Lite_SlaveInterface_B_HSEL,
    output reg  AHB_Lite_SlaveInterface_B_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_B_HRDATA,
    output reg  [31:0] AHB_Lite_SlaveInterface_B_HWDATA,
    output reg  [2:0] AHB_Lite_SlaveInterface_C_HSIZE,
    output reg  [1:0] AHB_Lite_SlaveInterface_C_HTRANS,
    input AHB_Lite_SlaveInterface_C_HRESP,
    input AHB_Lite_SlaveInterface_C_HREADY,
    output reg  AHB_Lite_SlaveInterface_C_HSEL,
    output reg  AHB_Lite_SlaveInterface_C_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_C_HRDATA,
    output reg  [31:0] AHB_Lite_SlaveInterface_C_HWDATA,
    output reg  [2:0] AHB_Lite_SlaveInterface_D_HSIZE,
    output reg  [1:0] AHB_Lite_SlaveInterface_D_HTRANS,
    input AHB_Lite_SlaveInterface_D_HRESP,
    input AHB_Lite_SlaveInterface_D_HREADY,
    output reg  AHB_Lite_SlaveInterface_D_HSEL,
    output reg  AHB_Lite_SlaveInterface_D_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_D_HRDATA,
    output reg  [31:0] AHB_Lite_SlaveInterface_D_HWDATA,
    output reg  [2:0] AHB_Lite_SlaveInterface_E_HSIZE,
    output reg  [1:0] AHB_Lite_SlaveInterface_E_HTRANS,
    input AHB_Lite_SlaveInterface_E_HRESP,
    input AHB_Lite_SlaveInterface_E_HREADY,
    output reg  AHB_Lite_SlaveInterface_E_HSEL,
    output reg  AHB_Lite_SlaveInterface_E_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_E_HRDATA,
    output reg  [31:0] AHB_Lite_SlaveInterface_E_HWDATA
);


always_comb
begin
    AHB_Lite_SlaveInterface_A_HSIZE = (slave_select == 3'b001) ? HSIZE : 3'b0;
    AHB_Lite_SlaveInterface_B_HSIZE = (slave_select == 3'b010) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_C_HSIZE = (slave_select == 3'b011) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_D_HSIZE = (slave_select == 3'b100) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_E_HSIZE = (slave_select == 3'b101) ? HSIZE : 3'b0;
end

always_comb
begin
    AHB_Lite_SlaveInterface_A_HTRANS = (slave_select == 3'b001) ? HTRANS : 2'b0;
    AHB_Lite_SlaveInterface_B_HTRANS = (slave_select == 3'b010) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_C_HTRANS = (slave_select == 3'b011) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_D_HTRANS = (slave_select == 3'b100) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_E_HTRANS = (slave_select == 3'b101) ? HTRANS : 2'b0;
end
always_comb
begin
    case (slave_select_delayed)
        3'b001 : HRESP = AHB_Lite_SlaveInterface_A_HRESP;
        3'b010 : HRESP = AHB_Lite_SlaveInterface_B_HRESP;
        3'b011 : HRESP = AHB_Lite_SlaveInterface_C_HRESP;
        3'b100 : HRESP = AHB_Lite_SlaveInterface_D_HRESP;
        3'b101 : HRESP = AHB_Lite_SlaveInterface_E_HRESP;
        default : HRESP = 1'b0;
    endcase
end
always_comb
begin
    case (slave_select_delayed)
        3'b001 : HREADY = AHB_Lite_SlaveInterface_A_HREADY;
        3'b010 : HREADY = AHB_Lite_SlaveInterface_B_HREADY;
        3'b011 : HREADY = AHB_Lite_SlaveInterface_C_HREADY;
        3'b100 : HREADY = AHB_Lite_SlaveInterface_D_HREADY;
        3'b101 : HREADY = AHB_Lite_SlaveInterface_E_HREADY;
        default : HREADY = 1'b1;
    endcase
end

always_comb
begin
    AHB_Lite_SlaveInterface_A_HSEL = (slave_select == 3'b001) ? HSEL : 1'b0;
    AHB_Lite_SlaveInterface_B_HSEL = (slave_select == 3'b010) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_C_HSEL = (slave_select == 3'b011) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_D_HSEL = (slave_select == 3'b100) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_E_HSEL = (slave_select == 3'b101) ? HSEL : 1'b0;
end

always_comb
begin
    AHB_Lite_SlaveInterface_A_HWRITE = (slave_select == 3'b001) ? HWRITE : 1'b0;
    AHB_Lite_SlaveInterface_B_HWRITE = (slave_select == 3'b010) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_C_HWRITE = (slave_select == 3'b011) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_D_HWRITE = (slave_select == 3'b100) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_E_HWRITE = (slave_select == 3'b101) ? HWRITE : 1'b0;
end
always_comb
begin
    case (slave_select_delayed)
        3'b001 : HRDATA = AHB_Lite_SlaveInterface_A_HRDATA;
        3'b010 : HRDATA = AHB_Lite_SlaveInterface_B_HRDATA;
        3'b011 : HRDATA = AHB_Lite_SlaveInterface_C_HRDATA;
        3'b100 : HRDATA = AHB_Lite_SlaveInterface_D_HRDATA;
        3'b101 : HRDATA = AHB_Lite_SlaveInterface_E_HRDATA;
        default : HRDATA = 32'b0;
    endcase
end

always_comb
begin
    AHB_Lite_SlaveInterface_A_HWDATA = (slave_select_delayed == 3'b001) ? HWDATA : 32'b0;
    AHB_Lite_SlaveInterface_B_HWDATA = (slave_select_delayed == 3'b010) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_C_HWDATA = (slave_select_delayed == 3'b011) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_D_HWDATA = (slave_select_delayed == 3'b100) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_E_HWDATA = (slave_select_delayed == 3'b101) ? HWDATA : 32'b0;
end

endmodule

