//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//
//
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_AddressDecoder_MasterInterface_1 (
    input [31:0] HADDR,
    output [2:0] slave_select,
    output reg  [2:0] slave_select_delayed,
    input HREADY,
    output [9:0] AHB_Lite_SlaveInterface_A_HADDR,
    output [9:0] AHB_Lite_SlaveInterface_B_HADDR,
    output [9:0] AHB_Lite_SlaveInterface_C_HADDR,
    output [9:0] AHB_Lite_SlaveInterface_D_HADDR,
    output [9:0] AHB_Lite_SlaveInterface_E_HADDR,
    input clk,
    input rst,
    input debug_ndmrst
);

wire   GTEQ_addressMin_0_Outp_s;
wire   LTEQ_addressMax_0_Outp_s;
wire   BAND_addressMatch_0_Outp_s;
wire   [31:0] HWMINUS_address_offset_AHB_Lite_SlaveInterface_A_HADDR_Outp_s;
wire   GTEQ_addressMin_1_Outp_s;
wire   LTEQ_addressMax_1_Outp_s;
wire   BAND_addressMatch_1_Outp_s;
wire   [31:0] HWMINUS_address_offset_AHB_Lite_SlaveInterface_B_HADDR_Outp_s;
wire   GTEQ_addressMin_2_Outp_s;
wire   LTEQ_addressMax_2_Outp_s;
wire   BAND_addressMatch_2_Outp_s;
wire   [31:0] HWMINUS_address_offset_AHB_Lite_SlaveInterface_C_HADDR_Outp_s;
wire   GTEQ_addressMin_3_Outp_s;
wire   LTEQ_addressMax_3_Outp_s;
wire   BAND_addressMatch_3_Outp_s;
wire   [31:0] HWMINUS_address_offset_AHB_Lite_SlaveInterface_D_HADDR_Outp_s;
wire   GTEQ_addressMin_4_Outp_s;
wire   LTEQ_addressMax_4_Outp_s;
wire   BAND_addressMatch_4_Outp_s;
wire   [31:0] HWMINUS_address_offset_AHB_Lite_SlaveInterface_E_HADDR_Outp_s;
wire   [4:0] CONCAT_inputVector_Outp_s;
reg   [2:0] LUT_slave_select_Outp_s;
always_comb
begin
    case (CONCAT_inputVector_Outp_s[4:0])
        5'b00001 : LUT_slave_select_Outp_s = 3'b001;
        5'b00010 : LUT_slave_select_Outp_s = 3'b010;
        5'b00100 : LUT_slave_select_Outp_s = 3'b011;
        5'b01000 : LUT_slave_select_Outp_s = 3'b100;
        5'b10000 : LUT_slave_select_Outp_s = 3'b101;
        default : LUT_slave_select_Outp_s = 3'b0;
    endcase
end
always_ff @(posedge rst, posedge clk)
begin
    if (rst == 1'b1) begin
        slave_select_delayed <= 3'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            slave_select_delayed <= 3'b0;
        end
        else if (HREADY == 1'b1) begin
            slave_select_delayed <= LUT_slave_select_Outp_s;
        end
    end
end
assign GTEQ_addressMin_0_Outp_s = HADDR >= 32'b0 ? 1'b1 : 1'b0;
assign LTEQ_addressMax_0_Outp_s = HADDR <= 32'b00000000000000000000001111100111 ? 1'b1 : 1'b0;
assign BAND_addressMatch_0_Outp_s = GTEQ_addressMin_0_Outp_s & LTEQ_addressMax_0_Outp_s;
assign HWMINUS_address_offset_AHB_Lite_SlaveInterface_A_HADDR_Outp_s = HADDR - 32'b0;
assign AHB_Lite_SlaveInterface_A_HADDR = HWMINUS_address_offset_AHB_Lite_SlaveInterface_A_HADDR_Outp_s[9:0];
assign GTEQ_addressMin_1_Outp_s = HADDR >= 32'b00000000000000000000001111101000 ? 1'b1 : 1'b0;
assign LTEQ_addressMax_1_Outp_s = HADDR <= 32'b00000000000000000000011111001111 ? 1'b1 : 1'b0;
assign BAND_addressMatch_1_Outp_s = GTEQ_addressMin_1_Outp_s & LTEQ_addressMax_1_Outp_s;
assign HWMINUS_address_offset_AHB_Lite_SlaveInterface_B_HADDR_Outp_s = HADDR - 32'b00000000000000000000001111101000;
assign AHB_Lite_SlaveInterface_B_HADDR = HWMINUS_address_offset_AHB_Lite_SlaveInterface_B_HADDR_Outp_s[9:0];
assign GTEQ_addressMin_2_Outp_s = HADDR >= 32'b00000000000000000000011111010000 ? 1'b1 : 1'b0;
assign LTEQ_addressMax_2_Outp_s = HADDR <= 32'b00000000000000000000101110110111 ? 1'b1 : 1'b0;
assign BAND_addressMatch_2_Outp_s = GTEQ_addressMin_2_Outp_s & LTEQ_addressMax_2_Outp_s;
assign HWMINUS_address_offset_AHB_Lite_SlaveInterface_C_HADDR_Outp_s = HADDR - 32'b00000000000000000000011111010000;
assign AHB_Lite_SlaveInterface_C_HADDR = HWMINUS_address_offset_AHB_Lite_SlaveInterface_C_HADDR_Outp_s[9:0];
assign GTEQ_addressMin_3_Outp_s = HADDR >= 32'b00000000000000000000101110111000 ? 1'b1 : 1'b0;
assign LTEQ_addressMax_3_Outp_s = HADDR <= 32'b00000000000000000000111110011111 ? 1'b1 : 1'b0;
assign BAND_addressMatch_3_Outp_s = GTEQ_addressMin_3_Outp_s & LTEQ_addressMax_3_Outp_s;
assign HWMINUS_address_offset_AHB_Lite_SlaveInterface_D_HADDR_Outp_s = HADDR - 32'b00000000000000000000101110111000;
assign AHB_Lite_SlaveInterface_D_HADDR = HWMINUS_address_offset_AHB_Lite_SlaveInterface_D_HADDR_Outp_s[9:0];
assign GTEQ_addressMin_4_Outp_s = HADDR >= 32'b00000000000000000000111110100000 ? 1'b1 : 1'b0;
assign LTEQ_addressMax_4_Outp_s = HADDR <= 32'b00000000000000000001001110000111 ? 1'b1 : 1'b0;
assign BAND_addressMatch_4_Outp_s = GTEQ_addressMin_4_Outp_s & LTEQ_addressMax_4_Outp_s;
assign HWMINUS_address_offset_AHB_Lite_SlaveInterface_E_HADDR_Outp_s = HADDR - 32'b00000000000000000000111110100000;
assign AHB_Lite_SlaveInterface_E_HADDR = HWMINUS_address_offset_AHB_Lite_SlaveInterface_E_HADDR_Outp_s[9:0];
assign CONCAT_inputVector_Outp_s = {BAND_addressMatch_4_Outp_s,BAND_addressMatch_3_Outp_s,BAND_addressMatch_2_Outp_s,BAND_addressMatch_1_Outp_s,BAND_addressMatch_0_Outp_s};
assign slave_select = LUT_slave_select_Outp_s;

endmodule

