//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:16    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_InputStage_MasterInterface_2 (
    input IS_MasterInterface_2_HREADY,
    input [2:0] AHB_Lite_MasterInterface_2_HSIZE,
    output [2:0] IS_MasterInterface_2_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_2_HTRANS,
    output [1:0] IS_MasterInterface_2_HTRANS,
    output AHB_Lite_MasterInterface_2_HRESP,
    input IS_MasterInterface_2_HRESP,
    output AHB_Lite_MasterInterface_2_HREADY,
    input [31:0] AHB_Lite_MasterInterface_2_HADDR,
    output [31:0] IS_MasterInterface_2_HADDR,
    input AHB_Lite_MasterInterface_2_HWRITE,
    output IS_MasterInterface_2_HWRITE,
    output [31:0] AHB_Lite_MasterInterface_2_HRDATA,
    input [31:0] IS_MasterInterface_2_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_2_HWDATA,
    output [31:0] IS_MasterInterface_2_HWDATA,
    input [3:0] AHB_Lite_MasterInterface_2_HPROT,
    output [3:0] IS_MasterInterface_2_HPROT,
    input [3:0] AHB_Lite_MasterInterface_2_HMASTER,
    output [3:0] IS_MasterInterface_2_HMASTER,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   NOT_Outp_s;

logic   [2:0] MasterInterface_2_HSIZE_cacheReg_Outp_s;
logic   [2:0] MasterInterface_2_HSIZE_cacheMux_Outp_s;
logic   [1:0] MasterInterface_2_HTRANS_cacheReg_Outp_s;
logic   [1:0] MasterInterface_2_HTRANS_cacheMux_Outp_s;
logic   [31:0] MasterInterface_2_HADDR_cacheReg_Outp_s;
logic   [31:0] MasterInterface_2_HADDR_cacheMux_Outp_s;
logic   MasterInterface_2_HWRITE_cacheReg_Outp_s;
logic   MasterInterface_2_HWRITE_cacheMux_Outp_s;
logic   [3:0] MasterInterface_2_HPROT_cacheReg_Outp_s;
logic   [3:0] MasterInterface_2_HPROT_cacheMux_Outp_s;
logic   [3:0] MasterInterface_2_HMASTER_cacheReg_Outp_s;
logic   [3:0] MasterInterface_2_HMASTER_cacheMux_Outp_s;

assign NOT_Outp_s = ~IS_MasterInterface_2_HREADY;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HSIZE_cacheReg_Outp_s <= 3'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HSIZE_cacheReg_Outp_s <= 3'b0;
        end else begin
            MasterInterface_2_HSIZE_cacheReg_Outp_s <= MasterInterface_2_HSIZE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HSIZE_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HSIZE;
        1'b1 : MasterInterface_2_HSIZE_cacheMux_Outp_s = MasterInterface_2_HSIZE_cacheReg_Outp_s;
        default : MasterInterface_2_HSIZE_cacheMux_Outp_s = 3'b0;
    endcase
end
assign IS_MasterInterface_2_HSIZE = MasterInterface_2_HSIZE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HTRANS_cacheReg_Outp_s <= 2'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HTRANS_cacheReg_Outp_s <= 2'b0;
        end else begin
            MasterInterface_2_HTRANS_cacheReg_Outp_s <= MasterInterface_2_HTRANS_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HTRANS_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HTRANS;
        1'b1 : MasterInterface_2_HTRANS_cacheMux_Outp_s = MasterInterface_2_HTRANS_cacheReg_Outp_s;
        default : MasterInterface_2_HTRANS_cacheMux_Outp_s = 2'b0;
    endcase
end
assign IS_MasterInterface_2_HTRANS = MasterInterface_2_HTRANS_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HADDR_cacheReg_Outp_s <= 32'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HADDR_cacheReg_Outp_s <= 32'b0;
        end else begin
            MasterInterface_2_HADDR_cacheReg_Outp_s <= MasterInterface_2_HADDR_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HADDR_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HADDR;
        1'b1 : MasterInterface_2_HADDR_cacheMux_Outp_s = MasterInterface_2_HADDR_cacheReg_Outp_s;
        default : MasterInterface_2_HADDR_cacheMux_Outp_s = 32'b0;
    endcase
end
assign IS_MasterInterface_2_HADDR = MasterInterface_2_HADDR_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HWRITE_cacheReg_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HWRITE_cacheReg_Outp_s <= 1'b0;
        end else begin
            MasterInterface_2_HWRITE_cacheReg_Outp_s <= MasterInterface_2_HWRITE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HWRITE_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HWRITE;
        1'b1 : MasterInterface_2_HWRITE_cacheMux_Outp_s = MasterInterface_2_HWRITE_cacheReg_Outp_s;
        default : MasterInterface_2_HWRITE_cacheMux_Outp_s = 1'b0;
    endcase
end
assign IS_MasterInterface_2_HWRITE = MasterInterface_2_HWRITE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HPROT_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HPROT_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_2_HPROT_cacheReg_Outp_s <= MasterInterface_2_HPROT_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HPROT_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HPROT;
        1'b1 : MasterInterface_2_HPROT_cacheMux_Outp_s = MasterInterface_2_HPROT_cacheReg_Outp_s;
        default : MasterInterface_2_HPROT_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_2_HPROT = MasterInterface_2_HPROT_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_HMASTER_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_HMASTER_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_2_HMASTER_cacheReg_Outp_s <= MasterInterface_2_HMASTER_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_2_HMASTER_cacheMux_Outp_s = AHB_Lite_MasterInterface_2_HMASTER;
        1'b1 : MasterInterface_2_HMASTER_cacheMux_Outp_s = MasterInterface_2_HMASTER_cacheReg_Outp_s;
        default : MasterInterface_2_HMASTER_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_2_HMASTER = MasterInterface_2_HMASTER_cacheMux_Outp_s;

assign AHB_Lite_MasterInterface_2_HRESP = IS_MasterInterface_2_HRESP;
assign AHB_Lite_MasterInterface_2_HREADY = IS_MasterInterface_2_HREADY;
assign AHB_Lite_MasterInterface_2_HRDATA = IS_MasterInterface_2_HRDATA;
assign IS_MasterInterface_2_HWDATA = AHB_Lite_MasterInterface_2_HWDATA;

endmodule

