//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:16    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_MasterSelect (
    input [1:0] master_select,
    input [1:0] master_select_delayed,
    output logic  [2:0] HSIZE,
    output logic  [1:0] HTRANS,
    input HRESP,
    input HREADY,
    output logic  HSEL,
    output logic  [31:0] HADDR,
    output logic  HWRITE,
    input [31:0] HRDATA,
    output logic  [31:0] HWDATA,
    output logic  HREADYIN,
    output logic  [3:0] HPROT,
    output logic  [3:0] HMASTER,
    input [2:0] AHB_Lite_MasterInterface_0_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_0_HTRANS,
    output logic  AHB_Lite_MasterInterface_0_HRESP,
    output logic  AHB_Lite_MasterInterface_0_HREADY,
    input MasterInterface_0_stalled,
    input AHB_Lite_MasterInterface_0_HSEL,
    input [31:0] AHB_Lite_MasterInterface_0_HADDR,
    input AHB_Lite_MasterInterface_0_HWRITE,
    output logic  [31:0] AHB_Lite_MasterInterface_0_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_0_HWDATA,
    input AHB_Lite_MasterInterface_0_HREADYIN,
    input [3:0] AHB_Lite_MasterInterface_0_HPROT,
    input [3:0] AHB_Lite_MasterInterface_0_HMASTER,
    input [2:0] AHB_Lite_MasterInterface_1_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_1_HTRANS,
    output logic  AHB_Lite_MasterInterface_1_HRESP,
    output logic  AHB_Lite_MasterInterface_1_HREADY,
    input MasterInterface_1_stalled,
    input AHB_Lite_MasterInterface_1_HSEL,
    input [31:0] AHB_Lite_MasterInterface_1_HADDR,
    input AHB_Lite_MasterInterface_1_HWRITE,
    output logic  [31:0] AHB_Lite_MasterInterface_1_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_1_HWDATA,
    input AHB_Lite_MasterInterface_1_HREADYIN,
    input [3:0] AHB_Lite_MasterInterface_1_HPROT,
    input [3:0] AHB_Lite_MasterInterface_1_HMASTER,
    input [2:0] AHB_Lite_MasterInterface_2_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_2_HTRANS,
    output logic  AHB_Lite_MasterInterface_2_HRESP,
    output logic  AHB_Lite_MasterInterface_2_HREADY,
    input MasterInterface_2_stalled,
    input AHB_Lite_MasterInterface_2_HSEL,
    input [31:0] AHB_Lite_MasterInterface_2_HADDR,
    input AHB_Lite_MasterInterface_2_HWRITE,
    output logic  [31:0] AHB_Lite_MasterInterface_2_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_2_HWDATA,
    input AHB_Lite_MasterInterface_2_HREADYIN,
    input [3:0] AHB_Lite_MasterInterface_2_HPROT,
    input [3:0] AHB_Lite_MasterInterface_2_HMASTER,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   Demux_HREADY_Out00_s;
logic   Demux_HREADY_Out01_s;
logic   Demux_HREADY_Out02_s;
logic   MasterInterface_0_cache_Outp_s;
logic   MasterInterface_1_cache_Outp_s;
logic   MasterInterface_2_cache_Outp_s;

always_comb
begin
    case (master_select)
        2'b1 : HSIZE = AHB_Lite_MasterInterface_0_HSIZE;
        2'b10 : HSIZE = AHB_Lite_MasterInterface_1_HSIZE;
        2'b11 : HSIZE = AHB_Lite_MasterInterface_2_HSIZE;
        default : HSIZE = 3'b0;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HTRANS = AHB_Lite_MasterInterface_0_HTRANS;
        2'b10 : HTRANS = AHB_Lite_MasterInterface_1_HTRANS;
        2'b11 : HTRANS = AHB_Lite_MasterInterface_2_HTRANS;
        default : HTRANS = 2'b0;
    endcase
end


always_comb
begin
    AHB_Lite_MasterInterface_0_HRESP = (master_select_delayed == 2'b1) ? HRESP : 1'b0;
    AHB_Lite_MasterInterface_1_HRESP = (master_select_delayed == 2'b10) ? HRESP : 1'b0;AHB_Lite_MasterInterface_2_HRESP = (master_select_delayed == 2'b11) ? HRESP : 1'b0;
end


always_comb
begin
    Demux_HREADY_Out00_s = (master_select_delayed == 2'b1) ? HREADY : 1'b1;
    Demux_HREADY_Out01_s = (master_select_delayed == 2'b10) ? HREADY : 1'b1;Demux_HREADY_Out02_s = (master_select_delayed == 2'b11) ? HREADY : 1'b1;
end

always_comb
begin
    case (master_select)
        2'b1 : HSEL = AHB_Lite_MasterInterface_0_HSEL;
        2'b10 : HSEL = AHB_Lite_MasterInterface_1_HSEL;
        2'b11 : HSEL = AHB_Lite_MasterInterface_2_HSEL;
        default : HSEL = 1'b0;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HADDR = AHB_Lite_MasterInterface_0_HADDR;
        2'b10 : HADDR = AHB_Lite_MasterInterface_1_HADDR;
        2'b11 : HADDR = AHB_Lite_MasterInterface_2_HADDR;
        default : HADDR = 32'b0;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HWRITE = AHB_Lite_MasterInterface_0_HWRITE;
        2'b10 : HWRITE = AHB_Lite_MasterInterface_1_HWRITE;
        2'b11 : HWRITE = AHB_Lite_MasterInterface_2_HWRITE;
        default : HWRITE = 1'b0;
    endcase
end


always_comb
begin
    AHB_Lite_MasterInterface_0_HRDATA = (master_select_delayed == 2'b1) ? HRDATA : 32'b0;
    AHB_Lite_MasterInterface_1_HRDATA = (master_select_delayed == 2'b10) ? HRDATA : 32'b0;AHB_Lite_MasterInterface_2_HRDATA = (master_select_delayed == 2'b11) ? HRDATA : 32'b0;
end

always_comb
begin
    case (master_select_delayed)
        2'b1 : HWDATA = AHB_Lite_MasterInterface_0_HWDATA;
        2'b10 : HWDATA = AHB_Lite_MasterInterface_1_HWDATA;
        2'b11 : HWDATA = AHB_Lite_MasterInterface_2_HWDATA;
        default : HWDATA = 32'b0;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HREADYIN = AHB_Lite_MasterInterface_0_HREADYIN;
        2'b10 : HREADYIN = AHB_Lite_MasterInterface_1_HREADYIN;
        2'b11 : HREADYIN = AHB_Lite_MasterInterface_2_HREADYIN;
        default : HREADYIN = 1'b1;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HPROT = AHB_Lite_MasterInterface_0_HPROT;
        2'b10 : HPROT = AHB_Lite_MasterInterface_1_HPROT;
        2'b11 : HPROT = AHB_Lite_MasterInterface_2_HPROT;
        default : HPROT = 4'b0;
    endcase
end

always_comb
begin
    case (master_select)
        2'b1 : HMASTER = AHB_Lite_MasterInterface_0_HMASTER;
        2'b10 : HMASTER = AHB_Lite_MasterInterface_1_HMASTER;
        2'b11 : HMASTER = AHB_Lite_MasterInterface_2_HMASTER;
        default : HMASTER = 4'b0;
    endcase
end

always_comb
begin
    case (MasterInterface_0_cache_Outp_s)
        1'b0 : AHB_Lite_MasterInterface_0_HREADY = Demux_HREADY_Out00_s;
        1'b1 : AHB_Lite_MasterInterface_0_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_0_HREADY = 1'b0;
    endcase
end

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_cache_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_cache_Outp_s <= 1'b0;
        end else begin
            MasterInterface_0_cache_Outp_s <= MasterInterface_0_stalled;
        end
    end
end

always_comb
begin
    case (MasterInterface_1_cache_Outp_s)
        1'b0 : AHB_Lite_MasterInterface_1_HREADY = Demux_HREADY_Out01_s;
        1'b1 : AHB_Lite_MasterInterface_1_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_1_HREADY = 1'b0;
    endcase
end

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_cache_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_cache_Outp_s <= 1'b0;
        end else begin
            MasterInterface_1_cache_Outp_s <= MasterInterface_1_stalled;
        end
    end
end

always_comb
begin
    case (MasterInterface_2_cache_Outp_s)
        1'b0 : AHB_Lite_MasterInterface_2_HREADY = Demux_HREADY_Out02_s;
        1'b1 : AHB_Lite_MasterInterface_2_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_2_HREADY = 1'b0;
    endcase
end

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_cache_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_cache_Outp_s <= 1'b0;
        end else begin
            MasterInterface_2_cache_Outp_s <= MasterInterface_2_stalled;
        end
    end
end


endmodule

