//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:16    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_ArbitrationUnit (
    output [1:0] master_select,
    input [1:0] MasterInterface_0_HTRANS_single_transaction_active,
    input [1:0] MasterInterface_1_HTRANS_single_transaction_active,
    input [1:0] MasterInterface_2_HTRANS_single_transaction_active,
    output [1:0] master_select_delayed,
    input HREADY,
    output logic  MasterInterface_2_stalled,
    output logic  MasterInterface_1_stalled,
    output logic  MasterInterface_0_stalled,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   EQ_MasterInterface_0_single_transaction_active_Outp_s;
logic   EQ_MasterInterface_1_single_transaction_active_Outp_s;
logic   EQ_MasterInterface_2_single_transaction_active_Outp_s;
logic   NEQ00_Outp_s;
logic   BAND00_Outp_s;
logic   NEQ01_Outp_s;
logic   BAND01_Outp_s;
logic   NEQ02_Outp_s;
logic   BAND02_Outp_s;
logic   NEQ03_Outp_s;
logic   BAND03_Outp_s;

logic   [1:0] master_select_s_Outp_s;
logic   [1:0] register_master_select_Outp_s;
logic   [1:0] master_select_mux_Outp_s;

assign EQ_MasterInterface_0_single_transaction_active_Outp_s = MasterInterface_0_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;

assign EQ_MasterInterface_1_single_transaction_active_Outp_s = MasterInterface_1_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;

assign EQ_MasterInterface_2_single_transaction_active_Outp_s = MasterInterface_2_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;


always_comb
begin
    if (EQ_MasterInterface_2_single_transaction_active_Outp_s == 1'b1) begin
        master_select_s_Outp_s = 2'b11;
    end
    else if (EQ_MasterInterface_1_single_transaction_active_Outp_s == 1'b1) begin
        master_select_s_Outp_s = 2'b10;
    end
    else if (EQ_MasterInterface_0_single_transaction_active_Outp_s == 1'b1) begin
        master_select_s_Outp_s = 2'b1;
    end else begin
        master_select_s_Outp_s = 2'b0;
    end
end

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        register_master_select_Outp_s <= 2'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            register_master_select_Outp_s <= 2'b0;
        end
        else if (BAND00_Outp_s == 1'b1) begin
            register_master_select_Outp_s <= master_select_s_Outp_s;
        end
    end
end
assign master_select_delayed = register_master_select_Outp_s;

always_comb
begin
    case (HREADY)
        1'b0 : master_select_mux_Outp_s = register_master_select_Outp_s;
        1'b1 : master_select_mux_Outp_s = master_select_s_Outp_s;
        default : master_select_mux_Outp_s = 2'b0;
    endcase
end
assign master_select = master_select_mux_Outp_s;

assign NEQ00_Outp_s = master_select_s_Outp_s != 2'b0 ? 1'b1 : 1'b0;

assign BAND00_Outp_s = NEQ00_Outp_s & HREADY;

assign NEQ01_Outp_s = master_select_mux_Outp_s != 2'b11 ? 1'b1 : 1'b0;

assign BAND01_Outp_s = EQ_MasterInterface_2_single_transaction_active_Outp_s & NEQ01_Outp_s;

always_comb
begin
    case (BAND01_Outp_s)
        1'b0 : MasterInterface_2_stalled = 1'b0;
        1'b1 : MasterInterface_2_stalled = 1'b1;
        default : MasterInterface_2_stalled = 1'b0;
    endcase
end

assign NEQ02_Outp_s = master_select_mux_Outp_s != 2'b10 ? 1'b1 : 1'b0;

assign BAND02_Outp_s = EQ_MasterInterface_1_single_transaction_active_Outp_s & NEQ02_Outp_s;

always_comb
begin
    case (BAND02_Outp_s)
        1'b0 : MasterInterface_1_stalled = 1'b0;
        1'b1 : MasterInterface_1_stalled = 1'b1;
        default : MasterInterface_1_stalled = 1'b0;
    endcase
end

assign NEQ03_Outp_s = master_select_mux_Outp_s != 2'b1 ? 1'b1 : 1'b0;

assign BAND03_Outp_s = EQ_MasterInterface_0_single_transaction_active_Outp_s & NEQ03_Outp_s;

always_comb
begin
    case (BAND03_Outp_s)
        1'b0 : MasterInterface_0_stalled = 1'b0;
        1'b1 : MasterInterface_0_stalled = 1'b1;
        default : MasterInterface_0_stalled = 1'b0;
    endcase
end


endmodule

