//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:51:58    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_ErrorDetection_MasterInterface_0_StallFSM (
    input raise_stall,
    output logic  stall,
    input Clk,
    input AsyncRst,
    input SyncRst
);

parameter s0 = 1'b0;
parameter s1 = 1'b1;

logic   state;
logic   next_state;

always_ff @(posedge Clk, negedge AsyncRst)
begin
    if (AsyncRst == 1'b0) begin
        state <= s0;
    end else begin
        if (SyncRst == 1'b1) begin
            state <= s0;
        end else begin
            state <= next_state;
        end
    end
end
always_comb
begin
    next_state = state;
    case (state)
        s0 : begin
            if (raise_stall == 1'b1) begin
                next_state = s1;
            end
        end
        s1 : begin
            next_state = s0;
        end
        default : next_state = state;
    endcase
end

always_comb
begin
    case (state)
        s0 : begin
            case (raise_stall)
                1'b0 : stall = 1'b1;
                1'b1 : stall = 1'b0;
                default : stall = 1'b0;
            endcase
        end
        s1 : begin
            stall = 1'b1;
        end
        default : begin
            stall = 1'b0;
        end
    endcase
end

endmodule

