//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:16    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_InputStage_MasterInterface_1 (
    input IS_MasterInterface_1_HREADY,
    input [2:0] AHB_Lite_MasterInterface_1_HSIZE,
    output [2:0] IS_MasterInterface_1_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_1_HTRANS,
    output [1:0] IS_MasterInterface_1_HTRANS,
    output AHB_Lite_MasterInterface_1_HRESP,
    input IS_MasterInterface_1_HRESP,
    output AHB_Lite_MasterInterface_1_HREADY,
    input [31:0] AHB_Lite_MasterInterface_1_HADDR,
    output [31:0] IS_MasterInterface_1_HADDR,
    input AHB_Lite_MasterInterface_1_HWRITE,
    output IS_MasterInterface_1_HWRITE,
    output [31:0] AHB_Lite_MasterInterface_1_HRDATA,
    input [31:0] IS_MasterInterface_1_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_1_HWDATA,
    output [31:0] IS_MasterInterface_1_HWDATA,
    input [3:0] AHB_Lite_MasterInterface_1_HPROT,
    output [3:0] IS_MasterInterface_1_HPROT,
    input [3:0] AHB_Lite_MasterInterface_1_HMASTER,
    output [3:0] IS_MasterInterface_1_HMASTER,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   NOT_Outp_s;

logic   [2:0] MasterInterface_1_HSIZE_cacheReg_Outp_s;
logic   [2:0] MasterInterface_1_HSIZE_cacheMux_Outp_s;
logic   [1:0] MasterInterface_1_HTRANS_cacheReg_Outp_s;
logic   [1:0] MasterInterface_1_HTRANS_cacheMux_Outp_s;
logic   [31:0] MasterInterface_1_HADDR_cacheReg_Outp_s;
logic   [31:0] MasterInterface_1_HADDR_cacheMux_Outp_s;
logic   MasterInterface_1_HWRITE_cacheReg_Outp_s;
logic   MasterInterface_1_HWRITE_cacheMux_Outp_s;
logic   [3:0] MasterInterface_1_HPROT_cacheReg_Outp_s;
logic   [3:0] MasterInterface_1_HPROT_cacheMux_Outp_s;
logic   [3:0] MasterInterface_1_HMASTER_cacheReg_Outp_s;
logic   [3:0] MasterInterface_1_HMASTER_cacheMux_Outp_s;

assign NOT_Outp_s = ~IS_MasterInterface_1_HREADY;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HSIZE_cacheReg_Outp_s <= 3'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HSIZE_cacheReg_Outp_s <= 3'b0;
        end else begin
            MasterInterface_1_HSIZE_cacheReg_Outp_s <= MasterInterface_1_HSIZE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HSIZE_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HSIZE;
        1'b1 : MasterInterface_1_HSIZE_cacheMux_Outp_s = MasterInterface_1_HSIZE_cacheReg_Outp_s;
        default : MasterInterface_1_HSIZE_cacheMux_Outp_s = 3'b0;
    endcase
end
assign IS_MasterInterface_1_HSIZE = MasterInterface_1_HSIZE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HTRANS_cacheReg_Outp_s <= 2'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HTRANS_cacheReg_Outp_s <= 2'b0;
        end else begin
            MasterInterface_1_HTRANS_cacheReg_Outp_s <= MasterInterface_1_HTRANS_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HTRANS_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HTRANS;
        1'b1 : MasterInterface_1_HTRANS_cacheMux_Outp_s = MasterInterface_1_HTRANS_cacheReg_Outp_s;
        default : MasterInterface_1_HTRANS_cacheMux_Outp_s = 2'b0;
    endcase
end
assign IS_MasterInterface_1_HTRANS = MasterInterface_1_HTRANS_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HADDR_cacheReg_Outp_s <= 32'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HADDR_cacheReg_Outp_s <= 32'b0;
        end else begin
            MasterInterface_1_HADDR_cacheReg_Outp_s <= MasterInterface_1_HADDR_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HADDR_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HADDR;
        1'b1 : MasterInterface_1_HADDR_cacheMux_Outp_s = MasterInterface_1_HADDR_cacheReg_Outp_s;
        default : MasterInterface_1_HADDR_cacheMux_Outp_s = 32'b0;
    endcase
end
assign IS_MasterInterface_1_HADDR = MasterInterface_1_HADDR_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HWRITE_cacheReg_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HWRITE_cacheReg_Outp_s <= 1'b0;
        end else begin
            MasterInterface_1_HWRITE_cacheReg_Outp_s <= MasterInterface_1_HWRITE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HWRITE_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HWRITE;
        1'b1 : MasterInterface_1_HWRITE_cacheMux_Outp_s = MasterInterface_1_HWRITE_cacheReg_Outp_s;
        default : MasterInterface_1_HWRITE_cacheMux_Outp_s = 1'b0;
    endcase
end
assign IS_MasterInterface_1_HWRITE = MasterInterface_1_HWRITE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HPROT_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HPROT_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_1_HPROT_cacheReg_Outp_s <= MasterInterface_1_HPROT_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HPROT_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HPROT;
        1'b1 : MasterInterface_1_HPROT_cacheMux_Outp_s = MasterInterface_1_HPROT_cacheReg_Outp_s;
        default : MasterInterface_1_HPROT_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_1_HPROT = MasterInterface_1_HPROT_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_1_HMASTER_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_HMASTER_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_1_HMASTER_cacheReg_Outp_s <= MasterInterface_1_HMASTER_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_1_HMASTER_cacheMux_Outp_s = AHB_Lite_MasterInterface_1_HMASTER;
        1'b1 : MasterInterface_1_HMASTER_cacheMux_Outp_s = MasterInterface_1_HMASTER_cacheReg_Outp_s;
        default : MasterInterface_1_HMASTER_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_1_HMASTER = MasterInterface_1_HMASTER_cacheMux_Outp_s;

assign AHB_Lite_MasterInterface_1_HRESP = IS_MasterInterface_1_HRESP;
assign AHB_Lite_MasterInterface_1_HREADY = IS_MasterInterface_1_HREADY;
assign AHB_Lite_MasterInterface_1_HRDATA = IS_MasterInterface_1_HRDATA;
assign IS_MasterInterface_1_HWDATA = AHB_Lite_MasterInterface_1_HWDATA;

endmodule

