//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:17    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_InputStage_MasterInterface_0 (
    input IS_MasterInterface_0_HREADY,
    input [2:0] AHB_Lite_MasterInterface_0_HSIZE,
    output [2:0] IS_MasterInterface_0_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_0_HTRANS,
    output [1:0] IS_MasterInterface_0_HTRANS,
    output AHB_Lite_MasterInterface_0_HRESP,
    input IS_MasterInterface_0_HRESP,
    output AHB_Lite_MasterInterface_0_HREADY,
    input [31:0] AHB_Lite_MasterInterface_0_HADDR,
    output [31:0] IS_MasterInterface_0_HADDR,
    input AHB_Lite_MasterInterface_0_HWRITE,
    output IS_MasterInterface_0_HWRITE,
    output [31:0] AHB_Lite_MasterInterface_0_HRDATA,
    input [31:0] IS_MasterInterface_0_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_0_HWDATA,
    output [31:0] IS_MasterInterface_0_HWDATA,
    input [3:0] AHB_Lite_MasterInterface_0_HPROT,
    output [3:0] IS_MasterInterface_0_HPROT,
    input [3:0] AHB_Lite_MasterInterface_0_HMASTER,
    output [3:0] IS_MasterInterface_0_HMASTER,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   NOT_Outp_s;

logic   [2:0] MasterInterface_0_HSIZE_cacheReg_Outp_s;
logic   [2:0] MasterInterface_0_HSIZE_cacheMux_Outp_s;
logic   [1:0] MasterInterface_0_HTRANS_cacheReg_Outp_s;
logic   [1:0] MasterInterface_0_HTRANS_cacheMux_Outp_s;
logic   [31:0] MasterInterface_0_HADDR_cacheReg_Outp_s;
logic   [31:0] MasterInterface_0_HADDR_cacheMux_Outp_s;
logic   MasterInterface_0_HWRITE_cacheReg_Outp_s;
logic   MasterInterface_0_HWRITE_cacheMux_Outp_s;
logic   [3:0] MasterInterface_0_HPROT_cacheReg_Outp_s;
logic   [3:0] MasterInterface_0_HPROT_cacheMux_Outp_s;
logic   [3:0] MasterInterface_0_HMASTER_cacheReg_Outp_s;
logic   [3:0] MasterInterface_0_HMASTER_cacheMux_Outp_s;

assign NOT_Outp_s = ~IS_MasterInterface_0_HREADY;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HSIZE_cacheReg_Outp_s <= 3'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HSIZE_cacheReg_Outp_s <= 3'b0;
        end else begin
            MasterInterface_0_HSIZE_cacheReg_Outp_s <= MasterInterface_0_HSIZE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HSIZE_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HSIZE;
        1'b1 : MasterInterface_0_HSIZE_cacheMux_Outp_s = MasterInterface_0_HSIZE_cacheReg_Outp_s;
        default : MasterInterface_0_HSIZE_cacheMux_Outp_s = 3'b0;
    endcase
end
assign IS_MasterInterface_0_HSIZE = MasterInterface_0_HSIZE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HTRANS_cacheReg_Outp_s <= 2'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HTRANS_cacheReg_Outp_s <= 2'b0;
        end else begin
            MasterInterface_0_HTRANS_cacheReg_Outp_s <= MasterInterface_0_HTRANS_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HTRANS_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HTRANS;
        1'b1 : MasterInterface_0_HTRANS_cacheMux_Outp_s = MasterInterface_0_HTRANS_cacheReg_Outp_s;
        default : MasterInterface_0_HTRANS_cacheMux_Outp_s = 2'b0;
    endcase
end
assign IS_MasterInterface_0_HTRANS = MasterInterface_0_HTRANS_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HADDR_cacheReg_Outp_s <= 32'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HADDR_cacheReg_Outp_s <= 32'b0;
        end else begin
            MasterInterface_0_HADDR_cacheReg_Outp_s <= MasterInterface_0_HADDR_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HADDR_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HADDR;
        1'b1 : MasterInterface_0_HADDR_cacheMux_Outp_s = MasterInterface_0_HADDR_cacheReg_Outp_s;
        default : MasterInterface_0_HADDR_cacheMux_Outp_s = 32'b0;
    endcase
end
assign IS_MasterInterface_0_HADDR = MasterInterface_0_HADDR_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HWRITE_cacheReg_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HWRITE_cacheReg_Outp_s <= 1'b0;
        end else begin
            MasterInterface_0_HWRITE_cacheReg_Outp_s <= MasterInterface_0_HWRITE_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HWRITE_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HWRITE;
        1'b1 : MasterInterface_0_HWRITE_cacheMux_Outp_s = MasterInterface_0_HWRITE_cacheReg_Outp_s;
        default : MasterInterface_0_HWRITE_cacheMux_Outp_s = 1'b0;
    endcase
end
assign IS_MasterInterface_0_HWRITE = MasterInterface_0_HWRITE_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HPROT_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HPROT_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_0_HPROT_cacheReg_Outp_s <= MasterInterface_0_HPROT_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HPROT_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HPROT;
        1'b1 : MasterInterface_0_HPROT_cacheMux_Outp_s = MasterInterface_0_HPROT_cacheReg_Outp_s;
        default : MasterInterface_0_HPROT_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_0_HPROT = MasterInterface_0_HPROT_cacheMux_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_0_HMASTER_cacheReg_Outp_s <= 4'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_0_HMASTER_cacheReg_Outp_s <= 4'b0;
        end else begin
            MasterInterface_0_HMASTER_cacheReg_Outp_s <= MasterInterface_0_HMASTER_cacheMux_Outp_s;
        end
    end
end

always_comb
begin
    case (NOT_Outp_s)
        1'b0 : MasterInterface_0_HMASTER_cacheMux_Outp_s = AHB_Lite_MasterInterface_0_HMASTER;
        1'b1 : MasterInterface_0_HMASTER_cacheMux_Outp_s = MasterInterface_0_HMASTER_cacheReg_Outp_s;
        default : MasterInterface_0_HMASTER_cacheMux_Outp_s = 4'b0;
    endcase
end
assign IS_MasterInterface_0_HMASTER = MasterInterface_0_HMASTER_cacheMux_Outp_s;

assign AHB_Lite_MasterInterface_0_HRESP = IS_MasterInterface_0_HRESP;
assign AHB_Lite_MasterInterface_0_HREADY = IS_MasterInterface_0_HREADY;
assign AHB_Lite_MasterInterface_0_HRDATA = IS_MasterInterface_0_HRDATA;
assign IS_MasterInterface_0_HWDATA = AHB_Lite_MasterInterface_0_HWDATA;

endmodule

