//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//
//
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_ArbitrationUnit_SlaveInterface_E (
    output [1:0] master_select,
    input [1:0] MasterInterface_0_HTRANS_single_transaction_active,
    input [1:0] MasterInterface_1_HTRANS_single_transaction_active,
    input [1:0] MasterInterface_2_HTRANS_single_transaction_active,
    output reg  MasterInterface_2_stalled,
    output reg  MasterInterface_1_stalled,
    output MasterInterface_0_stalled,
    output reg  [1:0] master_select_delayed,
    input HREADY,
    input clk,
    input rst,
    input debug_ndmrst
);

wire   EQ_MasterInterface_0_single_transaction_active_Outp_s;
wire   EQ_MasterInterface_1_single_transaction_active_Outp_s;
wire   EQ_MasterInterface_2_single_transaction_active_Outp_s;
wire   NEQ00_Outp_s;
wire   LAND00_Outp_s;
wire   NEQ01_Outp_s;
wire   LAND01_Outp_s;
reg   [1:0] Mux_prio_MasterInterface_2_Outp_s;
reg   [1:0] Mux_prio_MasterInterface_1_Outp_s;
reg   [1:0] Mux_prio_MasterInterface_0_Outp_s;
assign EQ_MasterInterface_0_single_transaction_active_Outp_s = MasterInterface_0_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;
assign EQ_MasterInterface_1_single_transaction_active_Outp_s = MasterInterface_1_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;
assign EQ_MasterInterface_2_single_transaction_active_Outp_s = MasterInterface_2_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;
always_comb
begin
    case (EQ_MasterInterface_2_single_transaction_active_Outp_s)
        1'b0 : Mux_prio_MasterInterface_2_Outp_s = 2'b0;
        1'b1 : Mux_prio_MasterInterface_2_Outp_s = 2'b11;
        default : Mux_prio_MasterInterface_2_Outp_s = 2'b0;
    endcase
end
assign NEQ00_Outp_s = Mux_prio_MasterInterface_2_Outp_s != Mux_prio_MasterInterface_0_Outp_s ? 1'b1 : 1'b0;
assign LAND00_Outp_s = NEQ00_Outp_s & EQ_MasterInterface_2_single_transaction_active_Outp_s;
always_ff @(posedge rst, posedge clk)
begin
    if (rst == 1'b1) begin
        MasterInterface_2_stalled <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_stalled <= 1'b0;
        end else begin
            MasterInterface_2_stalled <= LAND00_Outp_s;
        end
    end
end
always_comb
begin
    case (EQ_MasterInterface_1_single_transaction_active_Outp_s)
        1'b0 : Mux_prio_MasterInterface_1_Outp_s = Mux_prio_MasterInterface_2_Outp_s;
        1'b1 : Mux_prio_MasterInterface_1_Outp_s = 2'b10;
        default : Mux_prio_MasterInterface_1_Outp_s = 2'b0;
    endcase
end
assign NEQ01_Outp_s = Mux_prio_MasterInterface_1_Outp_s != Mux_prio_MasterInterface_0_Outp_s ? 1'b1 : 1'b0;
assign LAND01_Outp_s = NEQ01_Outp_s & EQ_MasterInterface_1_single_transaction_active_Outp_s;
always_ff @(posedge rst, posedge clk)
begin
    if (rst == 1'b1) begin
        MasterInterface_1_stalled <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_1_stalled <= 1'b0;
        end else begin
            MasterInterface_1_stalled <= LAND01_Outp_s;
        end
    end
end
always_comb
begin
    case (EQ_MasterInterface_0_single_transaction_active_Outp_s)
        1'b0 : Mux_prio_MasterInterface_0_Outp_s = Mux_prio_MasterInterface_1_Outp_s;
        1'b1 : Mux_prio_MasterInterface_0_Outp_s = 2'b01;
        default : Mux_prio_MasterInterface_0_Outp_s = 2'b0;
    endcase
end
always_ff @(posedge rst, posedge clk)
begin
    if (rst == 1'b1) begin
        master_select_delayed <= 2'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            master_select_delayed <= 2'b0;
        end
        else if (HREADY == 1'b1) begin
            master_select_delayed <= Mux_prio_MasterInterface_0_Outp_s;
        end
    end
end
assign master_select = Mux_prio_MasterInterface_0_Outp_s;
assign MasterInterface_0_stalled = 1'b0;

endmodule

