//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:16    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_ErrorDetection_MasterInterface_2 (
    input [2:0] slave_select,
    input HRESP_in,
    output logic  HRESP_out,
    input [1:0] MasterInterface_2_HTRANS_single_transaction_active,
    output HREADY_error,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   EQ_error_BA_Outp_s;
logic   EQ_MasterInterface_2_single_transaction_active_Outp_s;
logic   BAND_Outp_s;

logic   Mux_merge_error_BusAddressError_Outp_s;
logic   Mux_merge_error_MissalignmentError_Outp_s;
logic   MasterInterface_2_trans_reg_Outp_s;

assign EQ_error_BA_Outp_s = slave_select == 3'b0 ? 1'b1 : 1'b0;

always_comb
begin
    case (EQ_error_BA_Outp_s)
        1'b0 : Mux_merge_error_BusAddressError_Outp_s = HRESP_in;
        1'b1 : Mux_merge_error_BusAddressError_Outp_s = EQ_error_BA_Outp_s;
        default : Mux_merge_error_BusAddressError_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (1'b0)
        1'b0 : Mux_merge_error_MissalignmentError_Outp_s = Mux_merge_error_BusAddressError_Outp_s;
        1'b1 : Mux_merge_error_MissalignmentError_Outp_s = 1'b0;
        default : Mux_merge_error_MissalignmentError_Outp_s = 1'b0;
    endcase
end

assign EQ_MasterInterface_2_single_transaction_active_Outp_s = MasterInterface_2_HTRANS_single_transaction_active == 2'b10 ? 1'b1 : 1'b0;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        MasterInterface_2_trans_reg_Outp_s <= 1'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            MasterInterface_2_trans_reg_Outp_s <= 1'b0;
        end else begin
            MasterInterface_2_trans_reg_Outp_s <= EQ_MasterInterface_2_single_transaction_active_Outp_s;
        end
    end
end

always_comb
begin
    case (MasterInterface_2_trans_reg_Outp_s)
        1'b0 : HRESP_out = 1'b0;
        1'b1 : HRESP_out = Mux_merge_error_MissalignmentError_Outp_s;
        default : HRESP_out = 1'b0;
    endcase
end

assign BAND_Outp_s = MasterInterface_2_trans_reg_Outp_s & EQ_error_BA_Outp_s;

Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_ErrorDetection_MasterInterface_2_StallFSM comp_StallFSM(
    .raise_stall ( BAND_Outp_s  ),
    .Clk         ( clk          ),
    .AsyncRst    ( rst          ),
    .SyncRst     ( debug_ndmrst ),
    .stall       ( HREADY_error )
);


endmodule

