//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:17    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AddressDecoder (
    input [31:0] HADDR,
    output [2:0] slave_select,
    output logic  [2:0] slave_select_delayed,
    output [31:0] AHB_Lite_SlaveInterface_C_HADDR,
    output [31:0] AHB_Lite_SlaveInterface_A_HADDR,
    output [31:0] AHB_Lite_SlaveInterface_B_HADDR,
    output [31:0] AHB_Lite_SlaveInterface_D_HADDR,
    output [31:0] AHB_Lite_SlaveInterface_E_HADDR,
    output [31:0] AHB_Lite_SlaveInterface_F_HADDR,
    input clk,
    input rst,
    input debug_ndmrst
);

logic   GTEQ_addressMin_0_Outp_s;
logic   LTEQ_addressMax_0_Outp_s;
logic   BAND_addressMatch_0_Outp_s;
logic   GTEQ_addressMin_1_Outp_s;
logic   LTEQ_addressMax_1_Outp_s;
logic   BAND_addressMatch_1_Outp_s;
logic   GTEQ_addressMin_2_Outp_s;
logic   LTEQ_addressMax_2_Outp_s;
logic   BAND_addressMatch_2_Outp_s;
logic   GTEQ_addressMin_3_Outp_s;
logic   LTEQ_addressMax_3_Outp_s;
logic   BAND_addressMatch_3_Outp_s;
logic   GTEQ_addressMin_4_Outp_s;
logic   LTEQ_addressMax_4_Outp_s;
logic   BAND_addressMatch_4_Outp_s;
logic   GTEQ_addressMin_5_Outp_s;
logic   LTEQ_addressMax_5_Outp_s;
logic   BAND_addressMatch_5_Outp_s;
logic   [5:0] CONCAT_inputVector_Outp_s;

logic   [2:0] LUT_slave_select_Outp_s;

always_comb
begin
    case (CONCAT_inputVector_Outp_s[5:0])
        6'b000001 : LUT_slave_select_Outp_s = 3'b001;
        6'b000010 : LUT_slave_select_Outp_s = 3'b010;
        6'b000100 : LUT_slave_select_Outp_s = 3'b011;
        6'b001000 : LUT_slave_select_Outp_s = 3'b100;
        6'b010000 : LUT_slave_select_Outp_s = 3'b101;
        6'b100000 : LUT_slave_select_Outp_s = 3'b110;
        default : LUT_slave_select_Outp_s = 3'b0;
    endcase
end
assign slave_select = LUT_slave_select_Outp_s;

always_ff @(negedge rst, posedge clk)
begin
    if (rst == 1'b0) begin
        slave_select_delayed <= 3'b0;
    end else begin
        if (debug_ndmrst == 1'b1) begin
            slave_select_delayed <= 3'b0;
        end else begin
            slave_select_delayed <= LUT_slave_select_Outp_s;
        end
    end
end

assign GTEQ_addressMin_0_Outp_s = HADDR >= 32'b0 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_0_Outp_s = HADDR <= 32'b11111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_0_Outp_s = GTEQ_addressMin_0_Outp_s & LTEQ_addressMax_0_Outp_s;

assign GTEQ_addressMin_1_Outp_s = HADDR >= 32'b10001111111111111100000000000 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_1_Outp_s = HADDR <= 32'b10010000000111111111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_1_Outp_s = GTEQ_addressMin_1_Outp_s & LTEQ_addressMax_1_Outp_s;

assign GTEQ_addressMin_2_Outp_s = HADDR >= 32'b11000000000000000000000000000 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_2_Outp_s = HADDR <= 32'b11000000000000111111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_2_Outp_s = GTEQ_addressMin_2_Outp_s & LTEQ_addressMax_2_Outp_s;

assign GTEQ_addressMin_3_Outp_s = HADDR >= 32'b1000000000000000000000000000000 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_3_Outp_s = HADDR <= 32'b1000111111111111111111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_3_Outp_s = GTEQ_addressMin_3_Outp_s & LTEQ_addressMax_3_Outp_s;

assign GTEQ_addressMin_4_Outp_s = HADDR >= 32'b1001000000000000000000000000000 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_4_Outp_s = HADDR <= 32'b1011111111111111111111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_4_Outp_s = GTEQ_addressMin_4_Outp_s & LTEQ_addressMax_4_Outp_s;

assign GTEQ_addressMin_5_Outp_s = HADDR >= 32'b10111111111111110000000000000 ? 1'b1 : 1'b0;

assign LTEQ_addressMax_5_Outp_s = HADDR <= 32'b10111111111111111111111111111 ? 1'b1 : 1'b0;

assign BAND_addressMatch_5_Outp_s = GTEQ_addressMin_5_Outp_s & LTEQ_addressMax_5_Outp_s;

assign CONCAT_inputVector_Outp_s = {BAND_addressMatch_5_Outp_s,BAND_addressMatch_4_Outp_s,BAND_addressMatch_3_Outp_s,BAND_addressMatch_2_Outp_s,BAND_addressMatch_1_Outp_s,BAND_addressMatch_0_Outp_s};

assign AHB_Lite_SlaveInterface_C_HADDR = HADDR;
assign AHB_Lite_SlaveInterface_A_HADDR = HADDR;
assign AHB_Lite_SlaveInterface_B_HADDR = HADDR;
assign AHB_Lite_SlaveInterface_D_HADDR = HADDR;
assign AHB_Lite_SlaveInterface_E_HADDR = HADDR;
assign AHB_Lite_SlaveInterface_F_HADDR = HADDR;

endmodule

