//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//
//
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_AHB_Lite_AHB_Lite_MasterSelect_SlaveInterface_E (
    input [1:0] master_select,
    input [1:0] master_select_delayed,
    output reg  [2:0] HSIZE,
    output reg  [1:0] HTRANS,
    input HRESP,
    input HREADY,
    output reg  HSEL,
    output reg  [9:0] HADDR,
    output reg  HWRITE,
    input [31:0] HRDATA,
    output reg  [31:0] HWDATA,
    input [2:0] AHB_Lite_MasterInterface_0_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_0_HTRANS,
    output reg  AHB_Lite_MasterInterface_0_HRESP,
    output reg  AHB_Lite_MasterInterface_0_HREADY,
    input MasterInterface_0_stalled,
    input AHB_Lite_MasterInterface_0_HSEL,
    input [9:0] AHB_Lite_MasterInterface_0_HADDR,
    input AHB_Lite_MasterInterface_0_HWRITE,
    output reg  [31:0] AHB_Lite_MasterInterface_0_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_0_HWDATA,
    input [2:0] AHB_Lite_MasterInterface_1_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_1_HTRANS,
    output reg  AHB_Lite_MasterInterface_1_HRESP,
    output reg  AHB_Lite_MasterInterface_1_HREADY,
    input MasterInterface_1_stalled,
    input AHB_Lite_MasterInterface_1_HSEL,
    input [9:0] AHB_Lite_MasterInterface_1_HADDR,
    input AHB_Lite_MasterInterface_1_HWRITE,
    output reg  [31:0] AHB_Lite_MasterInterface_1_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_1_HWDATA,
    input [2:0] AHB_Lite_MasterInterface_2_HSIZE,
    input [1:0] AHB_Lite_MasterInterface_2_HTRANS,
    output reg  AHB_Lite_MasterInterface_2_HRESP,
    output reg  AHB_Lite_MasterInterface_2_HREADY,
    input MasterInterface_2_stalled,
    input AHB_Lite_MasterInterface_2_HSEL,
    input [9:0] AHB_Lite_MasterInterface_2_HADDR,
    input AHB_Lite_MasterInterface_2_HWRITE,
    output reg  [31:0] AHB_Lite_MasterInterface_2_HRDATA,
    input [31:0] AHB_Lite_MasterInterface_2_HWDATA
);

reg   Demux_HREADY_Out00_s;
reg   Demux_HREADY_Out01_s;
reg   Demux_HREADY_Out02_s;
always_comb
begin
    case (master_select)
        2'b01 : HSIZE = AHB_Lite_MasterInterface_0_HSIZE;
        2'b10 : HSIZE = AHB_Lite_MasterInterface_1_HSIZE;
        2'b11 : HSIZE = AHB_Lite_MasterInterface_2_HSIZE;
        default : HSIZE = 3'b0;
    endcase
end
always_comb
begin
    case (master_select)
        2'b01 : HTRANS = AHB_Lite_MasterInterface_0_HTRANS;
        2'b10 : HTRANS = AHB_Lite_MasterInterface_1_HTRANS;
        2'b11 : HTRANS = AHB_Lite_MasterInterface_2_HTRANS;
        default : HTRANS = 2'b0;
    endcase
end

always_comb
begin
    AHB_Lite_MasterInterface_0_HRESP = (master_select_delayed == 2'b01) ? HRESP : 1'b0;
    AHB_Lite_MasterInterface_1_HRESP = (master_select_delayed == 2'b10) ? HRESP : 1'b0;AHB_Lite_MasterInterface_2_HRESP = (master_select_delayed == 2'b11) ? HRESP : 1'b0;
end

always_comb
begin
    Demux_HREADY_Out00_s = (master_select_delayed == 2'b01) ? HREADY : 1'b1;
    Demux_HREADY_Out01_s = (master_select_delayed == 2'b10) ? HREADY : 1'b1;Demux_HREADY_Out02_s = (master_select_delayed == 2'b11) ? HREADY : 1'b1;
end
always_comb
begin
    case (master_select)
        2'b01 : HSEL = AHB_Lite_MasterInterface_0_HSEL;
        2'b10 : HSEL = AHB_Lite_MasterInterface_1_HSEL;
        2'b11 : HSEL = AHB_Lite_MasterInterface_2_HSEL;
        default : HSEL = 1'b0;
    endcase
end
always_comb
begin
    case (master_select)
        2'b01 : HADDR = AHB_Lite_MasterInterface_0_HADDR;
        2'b10 : HADDR = AHB_Lite_MasterInterface_1_HADDR;
        2'b11 : HADDR = AHB_Lite_MasterInterface_2_HADDR;
        default : HADDR = 10'b0;
    endcase
end
always_comb
begin
    case (master_select)
        2'b01 : HWRITE = AHB_Lite_MasterInterface_0_HWRITE;
        2'b10 : HWRITE = AHB_Lite_MasterInterface_1_HWRITE;
        2'b11 : HWRITE = AHB_Lite_MasterInterface_2_HWRITE;
        default : HWRITE = 1'b0;
    endcase
end

always_comb
begin
    AHB_Lite_MasterInterface_0_HRDATA = (master_select_delayed == 2'b01) ? HRDATA : 32'b0;
    AHB_Lite_MasterInterface_1_HRDATA = (master_select_delayed == 2'b10) ? HRDATA : 32'b0;AHB_Lite_MasterInterface_2_HRDATA = (master_select_delayed == 2'b11) ? HRDATA : 32'b0;
end
always_comb
begin
    case (master_select_delayed)
        2'b01 : HWDATA = AHB_Lite_MasterInterface_0_HWDATA;
        2'b10 : HWDATA = AHB_Lite_MasterInterface_1_HWDATA;
        2'b11 : HWDATA = AHB_Lite_MasterInterface_2_HWDATA;
        default : HWDATA = 32'b0;
    endcase
end
always_comb
begin
    case (MasterInterface_0_stalled)
        1'b0 : AHB_Lite_MasterInterface_0_HREADY = Demux_HREADY_Out00_s;
        1'b1 : AHB_Lite_MasterInterface_0_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_0_HREADY = 1'b0;
    endcase
end
always_comb
begin
    case (MasterInterface_1_stalled)
        1'b0 : AHB_Lite_MasterInterface_1_HREADY = Demux_HREADY_Out01_s;
        1'b1 : AHB_Lite_MasterInterface_1_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_1_HREADY = 1'b0;
    endcase
end
always_comb
begin
    case (MasterInterface_2_stalled)
        1'b0 : AHB_Lite_MasterInterface_2_HREADY = Demux_HREADY_Out02_s;
        1'b1 : AHB_Lite_MasterInterface_2_HREADY = 1'b0;
        default : AHB_Lite_MasterInterface_2_HREADY = 1'b0;
    endcase
end

endmodule

