//-------------------------------------------------------------------------
//---- AUTO GENERATED by METARTL, a METAGEN application
//---- Contact: ParitoshKumar.Sinha@infineon.com
//---- Contact: Yash.Ranjan@infineon.com
//---- Contact: Sebastian.Prebeck@infineon.com
//---- Copyrights (C) 2009-2023 Infineon Technologies AG
//
//---- Author      :   tahiraga
//---- Generated On:   15:53:17    29/09/2024
//
//-------------------------------------------------------------------------

module Top_RISCV_Subsystem_SlaveSelect (
    input [2:0] slave_select,
    input [2:0] slave_select_delayed,
    input [2:0] HSIZE,
    input [1:0] HTRANS,
    output logic  HRESP,
    output logic  HREADY,
    input HSEL,
    input HWRITE,
    output logic  [31:0] HRDATA,
    input [31:0] HWDATA,
    output logic  HREADYIN,
    input [3:0] HPROT,
    input [3:0] HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_C_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_C_HTRANS,
    input AHB_Lite_SlaveInterface_C_HRESP,
    input AHB_Lite_SlaveInterface_C_HREADY,
    output logic  AHB_Lite_SlaveInterface_C_HSEL,
    output logic  AHB_Lite_SlaveInterface_C_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_C_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_C_HWDATA,
    input AHB_Lite_SlaveInterface_C_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_C_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_C_HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_A_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_A_HTRANS,
    input AHB_Lite_SlaveInterface_A_HRESP,
    input AHB_Lite_SlaveInterface_A_HREADY,
    output logic  AHB_Lite_SlaveInterface_A_HSEL,
    output logic  AHB_Lite_SlaveInterface_A_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_A_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_A_HWDATA,
    input AHB_Lite_SlaveInterface_A_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_A_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_A_HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_B_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_B_HTRANS,
    input AHB_Lite_SlaveInterface_B_HRESP,
    input AHB_Lite_SlaveInterface_B_HREADY,
    output logic  AHB_Lite_SlaveInterface_B_HSEL,
    output logic  AHB_Lite_SlaveInterface_B_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_B_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_B_HWDATA,
    input AHB_Lite_SlaveInterface_B_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_B_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_B_HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_D_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_D_HTRANS,
    input AHB_Lite_SlaveInterface_D_HRESP,
    input AHB_Lite_SlaveInterface_D_HREADY,
    output logic  AHB_Lite_SlaveInterface_D_HSEL,
    output logic  AHB_Lite_SlaveInterface_D_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_D_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_D_HWDATA,
    input AHB_Lite_SlaveInterface_D_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_D_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_D_HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_E_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_E_HTRANS,
    input AHB_Lite_SlaveInterface_E_HRESP,
    input AHB_Lite_SlaveInterface_E_HREADY,
    output logic  AHB_Lite_SlaveInterface_E_HSEL,
    output logic  AHB_Lite_SlaveInterface_E_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_E_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_E_HWDATA,
    input AHB_Lite_SlaveInterface_E_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_E_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_E_HMASTER,
    output logic  [2:0] AHB_Lite_SlaveInterface_F_HSIZE,
    output logic  [1:0] AHB_Lite_SlaveInterface_F_HTRANS,
    input AHB_Lite_SlaveInterface_F_HRESP,
    input AHB_Lite_SlaveInterface_F_HREADY,
    output logic  AHB_Lite_SlaveInterface_F_HSEL,
    output logic  AHB_Lite_SlaveInterface_F_HWRITE,
    input [31:0] AHB_Lite_SlaveInterface_F_HRDATA,
    output logic  [31:0] AHB_Lite_SlaveInterface_F_HWDATA,
    input AHB_Lite_SlaveInterface_F_HREADYIN,
    output logic  [3:0] AHB_Lite_SlaveInterface_F_HPROT,
    output logic  [3:0] AHB_Lite_SlaveInterface_F_HMASTER
);



always_comb
begin
    AHB_Lite_SlaveInterface_C_HSIZE = (slave_select == 3'b1) ? HSIZE : 3'b0;
    AHB_Lite_SlaveInterface_A_HSIZE = (slave_select == 3'b10) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_B_HSIZE = (slave_select == 3'b11) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_D_HSIZE = (slave_select == 3'b100) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_E_HSIZE = (slave_select == 3'b101) ? HSIZE : 3'b0;AHB_Lite_SlaveInterface_F_HSIZE = (slave_select == 3'b110) ? HSIZE : 3'b0;
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HTRANS = (slave_select == 3'b1) ? HTRANS : 2'b0;
    AHB_Lite_SlaveInterface_A_HTRANS = (slave_select == 3'b10) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_B_HTRANS = (slave_select == 3'b11) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_D_HTRANS = (slave_select == 3'b100) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_E_HTRANS = (slave_select == 3'b101) ? HTRANS : 2'b0;AHB_Lite_SlaveInterface_F_HTRANS = (slave_select == 3'b110) ? HTRANS : 2'b0;
end

always_comb
begin
    case (slave_select_delayed)
        3'b1 : HRESP = AHB_Lite_SlaveInterface_C_HRESP;
        3'b10 : HRESP = AHB_Lite_SlaveInterface_A_HRESP;
        3'b11 : HRESP = AHB_Lite_SlaveInterface_B_HRESP;
        3'b100 : HRESP = AHB_Lite_SlaveInterface_D_HRESP;
        3'b101 : HRESP = AHB_Lite_SlaveInterface_E_HRESP;
        3'b110 : HRESP = AHB_Lite_SlaveInterface_F_HRESP;
        default : HRESP = 1'b0;
    endcase
end

always_comb
begin
    case (slave_select_delayed)
        3'b1 : HREADY = AHB_Lite_SlaveInterface_C_HREADY;
        3'b10 : HREADY = AHB_Lite_SlaveInterface_A_HREADY;
        3'b11 : HREADY = AHB_Lite_SlaveInterface_B_HREADY;
        3'b100 : HREADY = AHB_Lite_SlaveInterface_D_HREADY;
        3'b101 : HREADY = AHB_Lite_SlaveInterface_E_HREADY;
        3'b110 : HREADY = AHB_Lite_SlaveInterface_F_HREADY;
        default : HREADY = 1'b1;
    endcase
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HSEL = (slave_select == 3'b1) ? HSEL : 1'b0;
    AHB_Lite_SlaveInterface_A_HSEL = (slave_select == 3'b10) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_B_HSEL = (slave_select == 3'b11) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_D_HSEL = (slave_select == 3'b100) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_E_HSEL = (slave_select == 3'b101) ? HSEL : 1'b0;AHB_Lite_SlaveInterface_F_HSEL = (slave_select == 3'b110) ? HSEL : 1'b0;
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HWRITE = (slave_select == 3'b1) ? HWRITE : 1'b0;
    AHB_Lite_SlaveInterface_A_HWRITE = (slave_select == 3'b10) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_B_HWRITE = (slave_select == 3'b11) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_D_HWRITE = (slave_select == 3'b100) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_E_HWRITE = (slave_select == 3'b101) ? HWRITE : 1'b0;AHB_Lite_SlaveInterface_F_HWRITE = (slave_select == 3'b110) ? HWRITE : 1'b0;
end

always_comb
begin
    case (slave_select_delayed)
        3'b1 : HRDATA = AHB_Lite_SlaveInterface_C_HRDATA;
        3'b10 : HRDATA = AHB_Lite_SlaveInterface_A_HRDATA;
        3'b11 : HRDATA = AHB_Lite_SlaveInterface_B_HRDATA;
        3'b100 : HRDATA = AHB_Lite_SlaveInterface_D_HRDATA;
        3'b101 : HRDATA = AHB_Lite_SlaveInterface_E_HRDATA;
        3'b110 : HRDATA = AHB_Lite_SlaveInterface_F_HRDATA;
        default : HRDATA = 32'b0;
    endcase
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HWDATA = (slave_select_delayed == 3'b1) ? HWDATA : 32'b0;
    AHB_Lite_SlaveInterface_A_HWDATA = (slave_select_delayed == 3'b10) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_B_HWDATA = (slave_select_delayed == 3'b11) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_D_HWDATA = (slave_select_delayed == 3'b100) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_E_HWDATA = (slave_select_delayed == 3'b101) ? HWDATA : 32'b0;AHB_Lite_SlaveInterface_F_HWDATA = (slave_select_delayed == 3'b110) ? HWDATA : 32'b0;
end

always_comb
begin
    case (slave_select_delayed)
        3'b1 : HREADYIN = AHB_Lite_SlaveInterface_C_HREADYIN;
        3'b10 : HREADYIN = AHB_Lite_SlaveInterface_A_HREADYIN;
        3'b11 : HREADYIN = AHB_Lite_SlaveInterface_B_HREADYIN;
        3'b100 : HREADYIN = AHB_Lite_SlaveInterface_D_HREADYIN;
        3'b101 : HREADYIN = AHB_Lite_SlaveInterface_E_HREADYIN;
        3'b110 : HREADYIN = AHB_Lite_SlaveInterface_F_HREADYIN;
        default : HREADYIN = 1'b1;
    endcase
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HPROT = (slave_select == 3'b1) ? HPROT : 4'b0;
    AHB_Lite_SlaveInterface_A_HPROT = (slave_select == 3'b10) ? HPROT : 4'b0;AHB_Lite_SlaveInterface_B_HPROT = (slave_select == 3'b11) ? HPROT : 4'b0;AHB_Lite_SlaveInterface_D_HPROT = (slave_select == 3'b100) ? HPROT : 4'b0;AHB_Lite_SlaveInterface_E_HPROT = (slave_select == 3'b101) ? HPROT : 4'b0;AHB_Lite_SlaveInterface_F_HPROT = (slave_select == 3'b110) ? HPROT : 4'b0;
end


always_comb
begin
    AHB_Lite_SlaveInterface_C_HMASTER = (slave_select == 3'b1) ? HMASTER : 4'b0;
    AHB_Lite_SlaveInterface_A_HMASTER = (slave_select == 3'b10) ? HMASTER : 4'b0;AHB_Lite_SlaveInterface_B_HMASTER = (slave_select == 3'b11) ? HMASTER : 4'b0;AHB_Lite_SlaveInterface_D_HMASTER = (slave_select == 3'b100) ? HMASTER : 4'b0;AHB_Lite_SlaveInterface_E_HMASTER = (slave_select == 3'b101) ? HMASTER : 4'b0;AHB_Lite_SlaveInterface_F_HMASTER = (slave_select == 3'b110) ? HMASTER : 4'b0;
end


endmodule

